### ISSUE TITLE
Acts exits without command line option

### ISSUE THREAD

**Issue by jepace** [alexjurkiewicz/acts#10]
(I'm just starting to configure acts, so please forgive me if I'm confused).

When I run acts with no arguments, it fails with:
    # acts
    /usr/local/bin/acts: 1: parameter not set
    Exit

I suspect this is due to the "set -u", followed quickly by: if [ "$1" ...
That is, $1 isn't set since I have no command line arguments, which triggers the shell to terminate the program.

    # sh -x /usr/local/bin/acts
    + set -u
    + set -e
    + VERSION=1.2
    /usr/local/bin/acts: 1: parameter not set
    Exit 2

Running on FreeBSD 10.2.

**Comment by jepace** [comment]
I have verified that moving the "set -u" to after the check for --version works.

**Comment by alexjurkiewicz** [comment]
d'oh
