### ISSUE TITLE
New feature: Use a different source directory instead of /

### ISSUE THREAD

**Issue by jepace** [alexjurkiewicz/acts#11]
My use case involves backing up user data, and not the system itself.  For example, I want to backup /pool/UserData1 and /pool/UserData2.  Since these files are not in the root directory, and I don't want extraneous characters in my tarsnap archive names, I added a new variable "$backuproot", which tarsnaps relative to that instead of /.

```
> git diff acts
diff --git a/acts b/acts
index da1f966..0728751 100755
--- a/acts
+++ b/acts
@@ -137,13 +137,13 @@ fi
 # PART 3: Backup
 backuprc=0 # Notice any failed backups
 for dir in $backuptargets ; do
-    log_verbose "Backing up /$dir..."
+    log_verbose "Backing up $backuproot/$dir..."
     archive_starttime=$(date +%s)
     nicedirname=$(echo "$dir" | tr -d '/')
     # Uncontrolled expansion is bad, but we have little choice. See https://github.com/koalaman/shellcheck/wiki/Sc2086
     # shellcheck disable=SC2086
-    if ! output="$($tarsnap -c -f "$hostname-$archivetype-$today-$nicedirname" -C / $tarsnapbackupoptions "$dir" 2>&1)" ; then
-        log_message "Failed to back up \"$dir\"! ($output)"
+    if ! output="$($tarsnap -c -f "$hostname-$archivetype-$today-$nicedirname" -C $backuproot $tarsnapbackupoptions "$dir" 2>&1)" ; then
+        log_message "Failed to back up \"$backuproot/$dir\"! ($output)"
         backuprc=1
     fi
     archive_endtime=$(date +%s)

```

I don't actually know how to use git, so I hope this diff is sufficient if you want to include this for real.  Note that acts.conf.sample should also be updated to include this variable.  I have tested this for my one use case, but I probably messed things up, so please test first. :)

**Comment by alexjurkiewicz** [comment]
Thanks for the patch. I won't include this in acts since I suspect it's a niche need, but like #6 I'm open to receiving +1s.
