### ISSUE TITLE
Question: is coreutils 8.21 really required?

### ISSUE THREAD

**Issue by jjthrash** [alexjurkiewicz/acts#14]
I'm using the `.deb` to install to a production machine on a Ubuntu 12.04 machine. It requires coreutils 8.21, but 12.04 maxes out at 8.13. Do you think running with 8.13 will cause problems?

**Comment by sr** [comment]
I am pretty sure it isn’t. I only picked 8.21 because that’s what was on the machine I wrote the packaging code on (Ubuntu 15.10/Wily)

**Comment by jjthrash** [comment]
Great, thanks. No change needed for me, I can just make a special
fork for this.

On Mon, Jan 11, 2016, at 09:30 AM, Simon Rozet wrote:
> I am pretty sure it isn’t. I only picked 8.21 because that’s what was
> on the machine I wrote the packaging code on (Ubuntu 15.10/Wily)
>
>
> On 11 Jan 2016, at 15:13, Jimmy Thrasher
> <notifications@github.com> wrote:
>
>
>
> I'm using the .deb to install to a production machine on a Ubuntu
> 12.04 machine. It requires coreutils 8.21, but 12.04 maxes out at
> 8.13. Do you think running with 8.13 will cause problems?
>
>
>
> —
>
> Reply to this email directly or view it on GitHub
> <https://github.com/alexjurkiewicz/acts/issues/14>.
>
>
>
> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/alexjurkiewicz/acts/issues/14#issuecomment-170567686

**Comment by alexjurkiewicz** [comment]
I'll happily merge a PR reducing the coreutils version required to support
Ubuntu LTS

**Comment by jjthrash** [comment]
Created PR: https://github.com/alexjurkiewicz/acts/pull/15
