### ISSUE TITLE
sorry newbe :|  where do i find log files / feed back to confirm doing what i expect

### ISSUE THREAD

**Issue by mrhut10** [alexjurkiewicz/acts#16]
running it within cygwin on windows so far so good at least i think so.

where / how do i view the logs that it looks like it is logging so i can see its progress?

i'm assuming it must be about half way through backing up my folders but have no feedback to make sure it is getting the correct files.

thank you in advanced

**Comment by alexjurkiewicz** [comment]
Just to be clear, do you see the basic logging where it shows you what directory it's backing up? But you'd like logging for each file that's backed up, so you can confirm everything you expect is being saved properly?

There are two solutions:
1. Add `-v` to your tarsnap options, so tarsnap will print the name of each file it saves
2. Manually read the list of files in one of the backups `acts` makes, using a command like `tar tf <backupname>` which will list the files within the backup

**Comment by mrhut10** [comment]
that is all the information i'm seeing, i can see network traffic for the tarsnap service so i know it is running. but been a number of hours and wanting an estimation of how long will take.

1 ) missed oportunity to -v as already working,
2) how do i go about this? where are the tar files?

see screenshot of what i'm seeing

![acts progress feedback](https://cloud.githubusercontent.com/assets/20330237/16641640/1de0f008-4446-11e6-903b-7263b2399f0f.PNG)

**Comment by alexjurkiewicz** [comment]
You can't change the acts options while it's running, but you could cancel the run and start it again, if you wanted.

The tar files are stored in the tarsnap cloud, you can list all tarsnap archives with `tarsnap --list-archives`

**Comment by alexjurkiewicz** [comment]
Also, note that you can't pass arguments to `acts` directly (i see you tried to run `acts --dry-run`, which will have no effect). You should put these argument in your `acts.conf` file (see the README for more info).

**Comment by mrhut10** [comment]
yer i worked out that didn't do anything told you i was a newbie :(
i've turned on debug level feed back and set tarsnap="tarsnap -v" in config

and still this is all I'm seeing, is that normal? or should the -v option be providing more feed back?

![acts progress feedback2](https://cloud.githubusercontent.com/assets/20330237/16641894/75d357a4-4448-11e6-8b4f-13f090c1329a.PNG)

thank you again for your help so appreciated.

**Comment by mrhut10** [comment]
p.s. thats after i stopped it and restarted it with the new config.

**Comment by alexjurkiewicz** [comment]
Try adding -v to tarsnapbackupoptions instead

**Comment by mrhut10** [comment]
I did that and added dry run, but still only seeing details from your script,
is there a way to raise feedback that tarsnap is providing?

thats what i'm seeing, and sorry if i'm missing the point :(

![acts progress feedback3](https://cloud.githubusercontent.com/assets/20330237/16642247/5fe7d5ba-444c-11e6-84b6-6e414dcfeccb.PNG)

**Comment by alexjurkiewicz** [comment]
well, it looks like a few backups have completed now, so it might be easiest to inspect the tarsnap archive now, like `tarsnap -tf DESKTOP-94947K0-monthly-2016-07-07_03:53:22-cygdrivevwork`

**Comment by mrhut10** [comment]
looks like i may have fixed it,

within your script i put I added a "| tee progress.txt"
so when i open that file i can see it traversing through file system and feel confident it is working.

thank you again :)

this is the line that i've added the " | tee progress.txt"

`if ! output="$($tarsnap -c -f "$archivename" -C / $tarsnapbackupoptions "$dir" 2>&1 | tee progress.txt)" ; then`

**Comment by mrhut10** [comment]
is awesome as i know there are around 3000 files, and currently up to 2054 lines in file so i'm around 60% ish through the files structure

**Comment by mrhut10** [comment]
thank you again, i'll close off issue.
love your work :) thank you for creating.
