### ISSUE TITLE
Accept configuration path as argument

### ISSUE THREAD

**Issue by asymmetric** [alexjurkiewicz/acts#27]
I’m packaging acts for the nix package manager, and it would help if the paths to the configuration file weren’t hardcoded.

Are you open to this change? If so, I could probably come up with a PR.

**Comment by alexjurkiewicz** [comment]
That sounds reasonable. The behaviour if you pass this argument would be to
source only the specified file, and to fail if the file is unreadable. A
pull request would be welcome!

**Comment by asymmetric** [comment]
I would also then remove the implicit laoding of a file from the current directory, since people will be able to just specify the file explicitly. Cool?

**Comment by alexjurkiewicz** [comment]
Yes, I would be happy to see the end of that!
