### ISSUE TITLE
Can't backup /

### ISSUE THREAD

**Issue by assistcontrol** [alexjurkiewicz/acts#30]
This may be a niche problem, and it's entirely likely that I'm misusing tarsnap, but I have carefully set nodump flags throughout my filesystem, and run `tarsnap --nodump -c /`.

Setting `backuptargets="/"` works, but leads to strange-looking archive names. ACTS essentially unsets `$nicedirname`, leading to a dangling hyphen (`host-type-date-`). Setting `$backuptargets` to `.` produces odd names too (`host-type-date-.`). More ideal would be to just leave `$nicedirname` off entirely in that case (`host-type-date`).

Consider then:
```sh
if [ "$dir" = "/" ]; then
    nicedirname=""
else
    nicedirname=$(echo "-$dir" | tr -d '/')
```

and `s/-$nicedirname/$nicedirname/`.

**Comment by alexjurkiewicz** [comment]
Hey, thanks for these two reports. Bad news for getting them fixed though.
I don't use Tarsnap (and therefore acts) any more, so I'm not planning to
make any further changes to this project.

**Comment by assistcontrol** [comment]
Fair enough! I'll fork it and make the changes, and take a whack at a few of the other reported issues
