### ISSUE TITLE
cleaner archive names ?

### ISSUE THREAD

**Issue by simonmichael** [alexjurkiewicz/acts#37]
It would be nice if the generated archive names did not have the noisy backslash inserted (currently done to prevent the initial hyphen breaking printf I guess).

Also, I'd like it if the timestamp were optional - I'd prefer to have just the date in the archive name.

Thanks for acts!

**Comment by assistcontrol** [comment]
The optional timestamp would also require handling the case where a second backup is performed in a single day.

**Comment by simonmichael** [comment]
When using a name without timestamp, I'd expect it to overwrite a similarly named backup on the same day. (Mine is a one-backup-per-day situation.)

**Comment by assistcontrol** [comment]
The notion of clobbering backups is quite problematic, and not a path that acts should go down.

A `postbackupscript` could rename the backups (`tarsnap -c newname @@oldname && tarsnap -d oldname`).

To make that easier, what if acts supplied the names of backups created in a run as arguments to the `postbackupscript`?

**Comment by assistcontrol** [comment]
Oops, I completely forgot to reference this issue when I committed f1b5353. The backslash thing should be fixed there. You're correct that it was to prevent `printf` from breaking, but I think I've done it in a more intelligent way now.

@simonmichael: Does the final archive saved to tarsnap have a backslash in the name? If so I'll cut a new release immediately.

**Comment by assistcontrol** [comment]
Closing, as this should be working now. If anyone is getting mangled backup names, I'll let me know and I'll cut a new release ASAP.
