### ISSUE TITLE
Function 'nicedirname' doesn't work as expected

### ISSUE THREAD

**Issue by atueting** [alexjurkiewicz/acts#38]
`*) printf '\-%s' "$dirname" ;;`
With this code the archive always entails a backslash.

**Comment by assistcontrol** [comment]
Which OS are you using?

**Comment by assistcontrol** [comment]
`printf` is a finicky beast. And so is `echo`. Different OSes treat leading dashes differently, and I had to guess at a mechanism that would work everywhere.

It's true that `nicedirname` always includes a backslash, but it should have always interpolated away when included in strings. In retrospect, that simply wasn't a good approach.

I'm going to commit a different approach. Please, give it a try and let me know how it works for you.

**Comment by atueting** [comment]
Indeed, your patch fixed the issue!  Thanks for your quick turnaround!
