### ISSUE TITLE
Acts stuck on deletion

### ISSUE THREAD

**Issue by arichiardi** [alexjurkiewicz/acts#46]
Hi there and thanks for this tool, I use it regularly and with great delight :smile: 

There is a problem I think on deletion I cannot really identify: every time there is a backup to prune it kind of gets stuck at this:

```
Debug: daily
Debug: message="More than 31 daily backups, deleting the oldest"
Info: message="Deleting backup prefix xyz-daily-2020-12-02_18:19:16-var*"
Debug: message="Deleting backup xyz-daily-2020-12-02_18:19:16-var"
<stuck here>
```

I tried to delete the backup with vanilla `tarsnap` and it did that in no time.

I wonder what that can be? Any hint on how to debug?

**Comment by arichiardi** [comment]
I have noticed that if I do this in `prune_backups`, everything goes well:

```
log_debug "message=\"Deleting backup $archivetodel\""
$tarsnap -d -f "$archivetodel"    
#if ! output="$($tarsnap -d -f "$archivetodel" 2>&1)"; then
#    log_output=$(prettyprint log_output "$output")
#    log_message "delete-error type=$backuplevel output=\"$log_output\""
#fi
```

**Comment by arichiardi** [comment]
I see there is a new way to call `tarsnap` on `master` (not in the latest release).

https://github.com/alexjurkiewicz/acts/blob/master/acts#L103

I am going to try if it solves.

**Comment by arichiardi** [comment]
That indeed works, it might be good to cut a release with it, in the meantime many thanks!

**Comment by assistcontrol** [comment]
So you can confirm that it works for you on master? If you can confirm that then I'll cut a release.

**Comment by arichiardi** [comment]
@assistcontrol yes I can confirm

```
...
Info: message="Deleting backup prefix xyz-daily-2020-11-28_22:35:38-root*"
Debug: message="Deleting backup xyz-daily-2020-11-28_22:35:38-root"
Info: message="Deleting backup prefix xyz-daily-2020-11-28_21:41:18-root*"
Debug: message="Deleting backup xyz-daily-2020-11-28_21:41:18-root"
Info: message="Deleting backup prefix xyz-daily-2020-11-28_07:33:18-root*"
Debug: message="Deleting backup xyz-daily-2020-11-28_07:33:18-root"
Info: acts-finished duration=1019s action=exiting
```

**Comment by assistcontrol** [comment]
I've cut v1.4.2. Thanks, Andrea.
